### ISSUE TITLE
Frequency mismatch in FFT section of Feature Engineering notebook

### ISSUE THREAD

**Issue by BGerwe** [wesleybeckner/data_science_foundations#1]
In section 4.2.2 you synthesize some time-domain data and demonstrate FFTs for frequency analysis.
```
t = np.linspace(0,5,200)
w = 5
h = 4
s = 4 * h / np.pi * (np.sin(w*t) + np.sin(3*w*t)/3 + np.sin(5*w*t)/5)

# here is the call to numpy FFT
F = np.fft.fft(s)
freq = np.fft.fftfreq(t.shape[-1])

# amplitudes
amps = [max(np.sin(w*t)), max(np.sin(w*t*3)/3), max(np.sin(w*t*5)/5)]

fig, ax = plt.subplots(1,2,figsize=(10,5))

ax[0].plot(t,s)
ax[0].plot(t,np.sin(w*t), ls='--')
ax[0].plot(t,np.sin(w*t*3)/3, ls='--')
ax[0].plot(t,np.sin(w*t*5)/5, ls='--')
ax[0].set_title('Time Domain')

# tells us about the amplitude of the component at the
# corresponding frequency
magnitude = np.sqrt(F.real**2 + F.imag**2)

ax[1].plot(freq, magnitude)
ax[1].set_xlim(0,.15)
ax[1].set_title('Frequency Domain')
```

There are a couple of small problems that make the presentation non-intuitive. 
1. `w=5` is presumably to set the frequency at 5 Hz (period of 0.2s); however, looking at the time-domain plot, the waves have a period ~ 1.2 s. What's happening here is the _radial_ frequency is set to 5 and by extension the linear frequency is ~0.8 Hz (w / 2 * pi). This implicit conversion might be confusing to hawk-eyed students.
2. `freq = np.fft.fftfreq(t.shape[-1])` assumes a sampling time of 1 s, resulting in frequency bins that don't match the time-domain signal frequency. You'll notice the plotted FFTs have peaks around 0.02, 0.06, and 0.10 Hz; however, those peaks should appear at ~0.8, ~2.4, and ~4.0 Hz according to the implicit conversion pointed out in 1.
3. The amplitudes of the frequency domain don't match up with the time-domain signals. [FFT normalization](https://numpy.org/doc/stable/reference/routines.fft.html#normalization) can be a hairy issue... Here I would suggest normalizing by the size of the time-domain array and multiplying by 2. Why multiply by 2 you ask? Well, FFTs have positive and negative frequency branches, so the amplitude is split between those branches. Since you're only visualizing the positive frequency branch (as most people do!), it's more intuitive to show the amplitude as seen in the time-domain.
4. (nitpick) I love showing the sinusoidal components that contribute to the square wave; however, the plotted amplitudes of the constituent sin waves don't make that apparent
5. (nitpick) The FFT plot has a line at 0 across all the peaks. This is a consequence of how numpy arranges the FFT output by default. It zero-indexes the 0 Hz component, which is followed by the positive frequency components and _**then**_ the negative frequency components.
6. (nitpick) Time array size and sampling rate doesn't align with best-practices. The FFT should receive an integer number of cycles (kind of counterintuitively). The time between samples (`dt`) as defined is about 0.025s (`np.linspace(0, 5, 200)[1]`). So really the last sample should be at 5 - 0.025 = 4.975 s. This can create what is called "spectral leakage" where the power of components in the FFT is spread between multiple bins. It's not a huge deal here, but if the FFT is used as a model feature it could dilute feature importance.

All of these issues are addressed by the following:
```
t = np.linspace(0,1,501)
# FFT should be given an integer number of cycles so we leave out last sample
t = t[:-1] 
f = 5 # linear frequency in Hz
w = f * 2 * np.pi # radial frequency
h = 4 # height of square wave
amp = 4 * h / np.pi
s = amp * (np.sin(w*t) + np.sin(3*w*t)/3 + np.sin(5*w*t)/5)

# here is the call to numpy FFT
F = np.fft.fft(s)
freq = np.fft.fftfreq(t.shape[-1], d=t[1])

# reorder frequency spectrum and frequency bins with 0 Hz at the center
F = np.fft.fftshift(F)
freq = np.fft.fftshift(freq)
# scale frequency spectrum to correct amplitude
F = F / t.size

# amplitudes
amps = [max(np.sin(w*t)), max(np.sin(w*t*3)/3), max(np.sin(w*t*5)/5)]

fig, ax = plt.subplots(1,2,figsize=(10,5))

ax[0].plot(t,s)
ax[0].plot(t,amp * np.sin(w*t), ls='--')
ax[0].plot(t,amp * np.sin(w*t*3)/3, ls='--')
ax[0].plot(t,amp * np.sin(w*t*5)/5, ls='--')
ax[0].set_title('Time Domain')
ax[0].set_xlim(0, 1)
ax[0].set_xlabel('Time (s)')

# tells us about the amplitude of the component at the
# corresponding frequency. Multiplied by two because the
# signal power is split between (-) and (+) frequency branches
# of FFT, but we're only visualizing the (+) branch
magnitude = 2 * np.sqrt(F.real**2 + F.imag**2)

ax[1].plot(freq, magnitude)
ax[1].set_xlim(0, 30)
ax[1].set_xlabel('Frequency (Hz)')
ax[1].set_title('Frequency Domain')
```
![image](https://user-images.githubusercontent.com/38819321/146269155-c1c13bbb-a4b7-4363-a1e0-8e6cfefb6616.png)

**Comment by wesleybeckner** [comment]
Thanks @BGerwe, I've incorporated your changes [here](https://wesleybeckner.github.io/data_science_foundations/S4_Feature_Engineering/#4221-enrichment-fast-fourier-transform)!
